name: Sync
on:
  push:
    branches:
      - main
  workflow_dispatch:   # 👈 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          sudo apt update -y
          sudo apt-get install skopeo -y
      - name: git
        run: |
          cd ~
          mkdir k8s
          cd k8s
          git clone https://github.com/lsutils/utils.git
          cd ~
          git clone https://github.com/ls-2018/script.git
          cd script
          rm skopeo_copy_script.py || true
          rm trans_image.py || true
          rm sync_to_ls.com.py || true
          ln -s ~/k8s/utils/sync/skopeo_copy_script.py
          ln -s ~/k8s/utils/sync/trans_image.py
          ln -s ~/k8s/utils/sync/sync_to_ls.com.py
          chmod +x ./* || true

      - name: run
        run: |
          set -x
          cd ~
          ls 
          export PATH=`pwd`/script/:$PATH

#          python3 utils/sync/local_run.py
